name: Deploy yVPN

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: [self-hosted, yvpn]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove existing container if running
        run: |
          if [ "$(sudo docker ps -q -f name=yvpn_container)" ]; then
            docker stop yvpn_container
            docker rm yvpn_container
          fi

      - name: Build Docker container
        run: docker build -t yvpn:latest .

      - name: Run Docker container
        run: docker run -d -p 1337:1337 --name yvpn_container yvpn:latest

