name: Deploy yVPN

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner for building
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t yvpn:latest .

      - name: Save Docker image as a .tar file
        run: docker save yvpn:latest -o yvpn_image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: yvpn_image
          path: yvpn_image.tar

  deploy:
    runs-on: [self-hosted, yvpn]  # Self-hosted runner for deployment
    needs: build
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: yvpn_image
          path: .

      - name: Load Docker image
        run: docker load -i yvpn_image.tar

      - name: Clean up Docker container
        run: |
          # Stop and remove the existing container if it exists
          if [ "$(docker ps -aq -f name=yvpn)" ]; then
            docker stop yvpn || true
            docker rm -f yvpn || true
          fi

      - name: Run Docker container
        run: docker run -d -p 22:1337 --name yvpn yvpn:latest

