name: Deploy yVPN

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner for building
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t yvpn:latest .

      - name: Save Docker image as a .tar file
        run: docker save yvpn:latest -o yvpn_image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: yvpn_image
          path: yvpn_image.tar

  deploy:
    runs-on: [self-hosted, yvpn]  # Self-hosted runner for deployment
    needs: build
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: yvpn_image
          path: .

      - name: Load Docker image
        run: sudo docker load -i yvpn_image.tar
      
      - name: Clean up Docker containers and networks
        run: |
          # Stop and remove the existing container if it exists
          if [ "$(docker ps -aq -f name=yvpn_container)" ]; then
            sudo docker stop yvpn_container || true
            sudo docker rm -f yvpn_container || true
          fi
          # Remove any unused networks to free up resources
          sudo docker network prune -f


      - name: Ensure port 1337 is free
        run: |
          # Check and kill any processes using port 1337
          if lsof -i :1337; then
            PID=$(lsof -t -i :1337)
            echo "Killing process $PID using port 1337"
            sudo kill -9 $PID
          fi

      - name: Run Docker container with retry
        run: |
          for i in {1..3}; do
            sudo docker run -d -p 1337:22 --name yvpn_container yvpn:latest && break
            echo "Retrying in 5 seconds..."
            sleep 5
          done

